name: Create PR After Release-Please

on:
  pull_request:
    types: [closed]
    branches: [develop]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      # - name: Create Pull Request to release
      #   uses: peter-evans/create-pull-request@v6
      #   with:
      #     branch: develop
      #     base: release
      #     title: 'Merge develop into release after release-please PR is merged'
      #     body: 'Automated PR to merge develop into release after release-please PR is merged.'
      #     token: ${{ secrets.MY_RELESE_PLEASE_TOKEN }}
      - name: Reset promotion branch
        run: |
          git fetch origin release:release
          git reset --hard release
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          branch: production-promotion
          title: 'Merge develop into release after release-please PR is merged'
          body: 'Automated PR to merge develop into release after release-please PR is merged.'
          token: ${{ secrets.MY_RELESE_PLEASE_TOKEN }}
