name: Create PR After Release-Please

on:
  pull_request:
    types: [closed]
    branches: [develop]

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: create pr with gh cli
        id: check-pr
        env:
          GH_TOKEN:  ${{ secrets.MY_RELESE_PLEASE_TOKEN }}
        shell: bash
        run: |
          gh pr create --base release --head develop \
          --title "Merge develop into release after release-please PR is merged" \
          --body "Automated PR to merge develop into release after release-please PR is merged."
          ## check PR status

          # timeout seconds
          timeout=300
          interval=10
          elapsed=0
          TARGET_PR="Merge develop into release after release-please PR is merged"
          while [ $elapsed -lt $timeout ]; do
            echo "Checking PR list (attempt $((elapsed/interval + 1)))..."
            
            # get PR list and check target PR exist
            if gh pr list --search "$TARGET_PR" --state all | grep -q "$TARGET_PR"; then
              echo "::notice::Target PR found!"
              echo "pr_exists=true" >> $GITHUB_OUTPUT
              exit 0
            fi
            
            # wait for interval
            sleep $interval
            elapsed=$((elapsed + interval))
          done
          
          echo "::error::Timeout reached. Target PR not found."
          echo "pr_exists=false" >> $GITHUB_OUTPUT
          exit 1

      - name: update pr with empty commit with "feat:" to trigger please-please on release
        if: steps.check-pr.outputs.pr_exists == 'true'
        env:
          GH_TOKEN:  ${{ secrets.MY_RELESE_PLEASE_TOKEN }}
        run: |
          git co release-please--branches--develop--components--my-typescript-project
          git push
          git commit --allow-empty -m "feat: feat 8"
          git push