name: Release Please

on:
  push:
    branches: [release]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: windows-latest
    steps:
      - name: check pr source
        shell: bash
        id: check_pr_source
        run: |
          if [[ ${{ github.head_ref }} =~ master ]]; then
            echo "This is a PR from a master branch"
            echo "pr_from_master=true" >> $GITHUB_OUTPUT
          else
            echo "This is a PR from a non-master branch"
            echo "pr_from_master=false" >> $GITHUB_OUTPUT
          fi
      - name: skip release-please if pr is from master
        shell: bash
        run: |
          if [  "${{ steps.check_pr_source.outputs.pr_from_master }}" = "true" ]; then
            echo PR is from master, skip release-please"
            exit 0
      - name: Release Please on release
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          token: ${{ secrets.MY_RELESE_PLEASE_TOKEN }}
          target-branch: release
          #release-branch: release
