name: Release Please

on:
  push:
    branches: [develop]

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: windows-latest
    steps:
      - name: Release Please on develop
        uses: googleapis/release-please-action@v4
        with:
          release-type: node
          token: ${{ secrets.MY_RELESE_PLEASE_TOKEN }}
          target-branch: release